export const apiUrls = {
	users: {
		login: 'api/auth/login',
		create: 'api/auth/create_user',
		me: 'api/auth/get_me',
		getAll: 'api/auth/get_users',
		update: 'api/auth/update_user',
		upload: 'api/auth/upload',
		deleteMultiple: 'api/auth/delete_users',
	},
	hotels: {
		create: 'hotels/add_hotels',
		getAll: 'hotels/get_hotels',
		getOne: 'hotels/get_hotel_by_id',
		deleteMultiple: 'hotels/delete_hotels',
		upload: 'hotels/upload',
		updateOne: 'hotels/update_hotel_by_id',
	},
	umrahs: {
		create: 'umrahs',
		getAll: 'umrahs',
		getOne: 'umrahs',
		updateOne: 'umrahs',
		upload: 'umrahs/upload',
		deleteMultiple: 'umrahs/delete_umrahs',
	},
	transportations: {
		create: 'transportations/add_transportations',
		getAll: 'transportations/get_transportations',
		getOne: 'transportations/get_transportation_by_id',
		updateOne: 'transportations/update_transportation_by_id',
		upload: 'transportations/upload',
		deleteMultiple: 'transportations/delete_transportations',
	},
	clientDetails: {
		create: 'client_details/add_client_details',
		getAll: 'client_details/get_all_client_details',
		getOne: 'client_details/get_client_details_by_id',
		deleteMultiple: 'client_details/delete_client_details_by_id',
		upload: 'client_details/upload',
		updateOne: 'client_details/update_client_details_by_id',
	},
}
